image: sikalabs/ci

stages:
  - lint
  - plan
  - apply

variables:
  PLAN: plan.cache
  PLAN_JSON: plan.json
  PLAN_JSON_GITLAB: plan.gitlab.json

before_script:
  - shopt -s expand_aliases
  - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
  - cp $variables_auto_tfvars variables.auto.tfvars
  - cp $providers_auto_tfvars providers.auto.tfvars

terraform format check:
  stage: lint
  script:
    - make fmt-check

cache:
  paths:
    - .terraform

plan:
  stage: plan
  script:
    - terraform init
    - terraform plan -out=$PLAN
    - terraform show --json $PLAN > $PLAN_JSON
    - cat $PLAN_JSON | convert_report > $PLAN_JSON_GITLAB
    - infracost breakdown --path $PLAN_JSON --usage-file infracost-usage.yml
  artifacts:
    paths:
      - $PLAN
    reports:
      terraform: $PLAN_JSON_GITLAB

apply:
  stage: apply
  script:
    - terraform init
    - terraform apply $PLAN
  when: manual
  only:
    - master
